import 'package:metro_oct/GraphBuild/Station_class.dart';

List<String> location_name(){

  List<Station>StationList=parseJsonToStationList();

  List<String>delhiMetroStations=[];
  int size=StationList.length;
  Map<String,int>umap={};


  for(int i=0;i<size;i++){
    if(umap[StationList[i].name]==null){
      delhiMetroStations.add(StationList[i].name);
      umap[StationList[i].name]=1;
    }

  }
  //
  // List<String> delhiMetroStations = [
  //   'Noida Electronic City',
  //   'Noida Sector 62',
  //   'Noida Sector 59',
  //   'Noida Sector 61',
  //   'Noida Sector 52',
  //   'Noida Sector 34',
  //   'Noida City Center',
  //   'Golf Course',
  //   'Botanical Garden',
  //   'Noida Sector 18',
  //   'Noida Sector 16',
  //   'Noida Sector 15',
  //   'New Ashok Nagar',
  //   'Mayur Vihar Extension',
  //   'Mayur Vihar–I',
  //   'Akshardham',
  //   'Yamuna Bank',
  //   'Indraprastha',
  //   'Supreme Court',
  //   'Mandi House',
  //   'Barakhamba Road',
  //   'Rajiv Chowk',
  //   'Ramakrishna Ashram Marg',
  //   'Jhandewalan',
  //   'Karol Bagh',
  //   'Rajendra Place',
  //   'Patel Nagar',
  //   'Shadipur',
  //   'Moti Nagar',
  //   'Ramesh Nagar',
  //   'Rajouri Garden',
  //   'Tagore Garden',
  //   'Subhash Nagar',
  //   'Tilak Nagar',
  //   'Janakpuri East',
  //   'Janakpuri West',
  //   'Uttam Nagar East',
  //   'Uttam Nagar West',
  //   'Nawada',
  //   'Dwarka Mor',
  //   'Dwarka',
  //   'Dwarka Sector 14',
  //   'Dwarka Sector 13',
  //   'Dwarka Sector 12',
  //   'Dwarka Sector 11',
  //   'Dwarka Sector 10',
  //   'Dwarka Sector 9',
  //   'Dwarka Sector 8',
  //   'Dwarka Sector 21',
  //   "Vaishali",
  //   "Kaushambi",
  //   "Karkarduma",
  //   "Preet Vihar",
  //   "Nirman Vihar",
  //   "Laxmi Nagar", 'Inderlok',
  //   'Ashok Park Main',
  //   'Punjabi Bagh',
  //   'Shivaji Park',
  //   'Madipur',
  //   'Paschim Vihar East',
  //   'Paschim Vihar West',
  //   'Peera Garhi',
  //   'Udyog Nagar',
  //   'Surajmal Stadium',
  //   'Nangloi',
  //   'Nangloi Railway Station',
  //   'Rajdhani Park',
  //   'Mundka',
  //   'Mundka Industrial Area',
  //   'Ghevra',
  //   'Tikri Kalan',
  //   'Tikri Border',
  //   'Pandit Shree Ram Sharma',
  //   'Bahadurgarh City',
  //   'Brigadier Hoshiyar Singh',
  //       "Kirti Nagar",
  //       "Satguru Ram Singh Marg",
  //       "Ashok Park Main",
  //   "RK Ashram",
  //   "Nabi Karim",
  //   "Sadar Bazar",
  //   "Pul Bangash",
  //   "Subzi Mandi",
  //   "Shakti Nagar Chowk",
  //   "Derawal Nagar",
  //   "Ashok Vihar",
  //   "Azadpur",
  //   "Majlis Park",
  //   "Bhalswa Lake",
  //   "Mukarba Chowk",
  //   "Haiderpur Badli Mor",
  //   "North Pitampura",
  //   "Prashant Vihar",
  //   "Madhuban Chowk",
  //   "Deepali Chowk",
  //   "Pushpanjali",
  //   "West Enclave",
  //   "Mangolpuri",
  //   "Peeragarhi",
  //   "Paschim Vihar",
  //   "Meera Bagh",
  //   "Keshopur",
  //   "Krishna Park Extension",
  //   "Janakpuri West",
  //   'New Delhi',
  //   'Shivaji Stadium',
  //   'Dhaula Kuan',
  //   'Delhi Aerocity',
  //   'IGI Airport',
  //   'Dwarka Sector 21',
  //   "Shiv Vihar",
  //   "Johri Enclave",
  //   "Gokulpuri",
  //   "Maujpur Babarpur",
  //   'Jaffrabad',
  //   'Welcome',
  //   'East Azad Nagar',
  //   'Krishna Nagar',
  //   'Karkarduma Court',
  //   'Karkarduma',
  //   "Anand Vihar ISBT",
  //   'IP Extension',
  //   'Mandawali West Vinod Nagar',
  //   'East Vinod Nagar Mayur Vihar II',
  //   'Trilokpuri Sanjay Lake',
  //   'Mayur Vihar Pocket I',
  //   'Mayur Vihar I',
  //   'Sarai Kale Khan Nizamuddin',
  //   'Ashram',
  //   'Vinobapuri',
  //   'Lajpat Nagar',
  //   'South Extension',
  //   'Delhi Haat INA',
  //   'Sarojini Nagar',
  //   'Bhikaji Cama Place',
  //   'Sir Vishweshwaraiah Moti Bagh',
  //   'Durgabai Deshmukh South Campus',
  //   'Delhi Cantt',
  //   'Naraina Vihar',
  //   'Mayapuri',
  //   'Rajouri Garden',
  //   'ESI Hospital',
  //   'Punjabi Bagh West',
  //   'Shakurpur',
  //   'Netaji Subhash Place',
  //   'Shalimar Bagh',
  //   'Azadpur',
  //   'Majlis Park',
  //   "Shaheed Sthal",
  //   "Hindon",
  //   "Arthala",
  //   "Mohan Nagar",
  //   "Shyam park",
  //   "Major Mohit Sharma",
  //   "Raj Bagh",
  //   "Shaheed Nagar",
  //   "Dilshad Garden",
  //   "Jhilmil",
  //   "Mansarovar Park",
  //   "Shahdara",
  //   "Welcome",
  //   "Seelampur",
  //   "Shastri Park",
  //   "Kashmere Gate",
  //   "Tis Hazari",
  //   "Pul Bangash",
  //   "Pratap Nagar",
  //   "Shastri Nagar",
  //   "Inderlok",
  //   "Kanhiya Nagar",
  //   "Keshav Puram",
  //   "Netaji Subhash Place",
  //   "Kohat Enclave",
  //   "Pitam Pura",
  //   "Rohini East",
  //   "Rohini West",
  //   "Rithala",
  //   "Kashmere Gate",
  //   "Lal Qila",
  //   "Jama Masjid",
  //   "Delhi Gate",
  //   "ITO",
  //   "Mandi House",
  //   "Janpath",
  //   "Central Secretariat",
  //   "Khan Market",
  //   "Jawaharlal Nehru Stadium",
  //   "Jangpura",
  //   "Lajpat Nagar",
  //   "Moolchand",
  //   "Kailash Colony",
  //   "Nehru Place",
  //   "Kalkaji Mandir",
  //   "Govind Puri",
  //   "Harkesh Nagar",
  //   "Jasola Apollo",
  //   "Sarita Vihar",
  //   "Mohan Estate",
  //   "Tughlakabad",
  //   "Badarpur",
  //   "Sarai",
  //   "NHPC Chowk",
  //   "Mewla Maharajpur",
  //   "Sector 28",
  //   "Badkhal Mor",
  //   "Faridabad Old",
  //   "Neelam Chowk Ajronda",
  //   "Bata Chowk",
  //   "Escorts Mujesar",
  //   "Sant Surdas Sihi",
  //   "Raja Nahar Singh Ballabhgarh",
  //   "Samaypur Badli",
  //   "Rohini Sector 18 19",
  //   "Haiderpur Badli Mor",
  //   "Jahangirpuri",
  //   "Adarsh Nagar",
  //   "Azadpur",
  //   "Model Town",
  //   "GTB Nagar",
  //   "Vishwavidyalaya",
  //   "Vidhan Sabha",
  //   "Civil Lines",
  //   "Kashmere Gate",
  //   "Chandni Chowk",
  //   "Chawri Bazar",
  //   "New Delhi",
  //   "Rajiv Chowk",
  //   "Patel Chowk",
  //   "Central Secretariat",
  //   "Udyog Bhawan",
  //   "Lok Kalyan Marg",
  //   "Jor Bagh",
  //   "INA",
  //   "AIIMS",
  //   "Green Park",
  //   "Hauz Khas",
  //   "Malviya Nagar",
  //   "Saket",
  //   "Qutub Minar",
  //   "Chhatarpur",
  //   "Sultanpur",
  //   "Ghitorni",
  //   "Arjan Garh",
  //   "Guru Dronacharya",
  //   "Sikandarpur",
  //   "MG Road",
  //   "IFFCO Chowk",
  //   "HUDA City Centre",
  //   "Shaheed Sthal",
  //   "Hindon",
  //   "Arthala",
  //   "Mohan Nagar",
  //   "Shyam park",
  //   "Major Mohit Sharma",
  //   "Raj Bagh",
  //   "Shaheed Nagar",
  //   "Dilshad Garden",
  //   "Jhilmil",
  //   "Mansarovar Park",
  //   "Shahdara",
  //   "Welcome",
  //   "Seelampur",
  //   "Shastri Park",
  //   "Kashmere Gate",
  //   "Tis Hazari",
  //   "Pulbangash",
  //   "Pratap Nagar",
  //   "Shastri Nagar",
  //   "Inderlok",
  //   "Kanhiya Nagar",
  //   "Keshav Puram",
  //   "Netaji Subhash Place",
  //   "Kohat Enclave",
  //   "PitamPura",
  //   "Rohini East",
  //   "Rohini West",
  //   "Rithala"
  // ];

  return delhiMetroStations;
}